language: erlang

otp_release:
  - R16B03
  - R15B01

services:
  - riak

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install libexpat1-dev libyaml-dev libpam0g-dev

before_script:
  - sudo service riak status
  - sudo riak version

script:
  - ./autogen.sh
  - ./configure --disable-all --enable-riak
  - make xref
  - ERL_LIBS=$PWD make test
  - grep -q 'TEST COMPLETE, \([[:digit:]]*\) ok, .* of \1 ' logs/raw.log

after_script:
  - find logs -name suite.log -exec cat '{}' ';'

after_failure:
  - find logs -name ejabberd.log -exec cat '{}' ';'

notifications:
  email: false
